### ISSUE TITLE
Support `/` in Drip List titles

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1065] opened 2024-04-24 07:55 UTC
![image](https://github.com/drips-network/app/assets/4406983/d32b973f-66f7-4c71-8385-d9a65a7ef2fd)

https://www.drips.network/app/drip-lists/44233954899343831995062217275215737681377860849646413826815741964160

**Comment by efstajas** [comment] 2024-05-27 09:11
Can't repro this: https://sepolia.drips.network/app/drip-lists/34222222824579492339388252769189852861539276769563279135322976662298

The / looks strange but that's what it is in the font. Maybe it's something about the hindi character..? But I don't see any reason why it would be that

**Comment by efstajas** [comment] 2024-05-28 12:06
Closing bc unable to reproduce

**Closed by efstajas** 2024-05-28 12:06 UTC
Labels: polish
