### ISSUE TITLE
Show Drips Logo on mobile

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#962] opened 2024-02-13 19:03 UTC
at least when user's aren't connected. we could move the "Connect" button to the bottom edge of the screen, fixed? (wdyt @brandonhaslegs) then the menu would take it's place once connected.

<img width="437" alt="Screenshot 2024-02-13 at 20 01 34" src="https://github.com/drips-network/app/assets/6071219/74aa1602-48b9-405a-b7a0-1e3431cbfc04">

**Comment by brandonhaslegs** [comment] 2024-02-13 19:12
The Drips logo should fit fine here? no need to move the connect button?

**Comment by brandonhaslegs** [comment] 2024-02-14 14:40
duplicate of #957

**Closed by brandonhaslegs** 2024-02-14 14:40 UTC
